import fs from "fs";
import path from "path";
import { playfair } from "@/lib/fonts";
import Nav from "@/components/Nav";
import SectionLabel from "@/components/SectionLabel";
import StatGrid from "@/components/StatGrid";
import ComparisonRow from "@/components/ComparisonRow";
import CommonKeywords from "@/components/CommonKeywords";
import TopicDonut from "@/components/TopicDonut";
import TopicTrendsChart from "@/components/TopicTrendsChart";
import TopicPositionHeatmap from "@/components/TopicPositionHeatmap";
import PositionBalancePanel from "@/components/PositionBalancePanel";
import { BarChart } from "@/components/Charts";
import StrengthBandChart from "@/components/StrengthBandChart";
import { topKeywords } from "@/lib/keywords";

function loadJson(filename) {
  const filePath = path.join(process.cwd(), "public", "data", filename);
  return JSON.parse(fs.readFileSync(filePath, "utf-8"));
}

// Some exports (currently just strength_bands.json) are generated by a step
// that needs the full local database and may not have been run yet. Treat a
// missing file as "no data" rather than failing the build - the component
// renders an explicit empty state with the exact command to fix it.
function loadJsonOptional(filename) {
  const filePath = path.join(process.cwd(), "public", "data", filename);
  if (!fs.existsSync(filePath)) return null;
  return JSON.parse(fs.readFileSync(filePath, "utf-8"));
}

function formatTerm(term) {
  if (term === "Intercept") return "Intercept";
  if (term === "prior_rank_centered") return "Prior team rank (centered)";
  if (term === "final_rank_centered") return "Final team rank (centered)";
  const match = term.match(/C\(position, Treatment\(reference='OG'\)\)\[T\.(\w+)\]/);
  if (match) return `${match[1]} vs. OG`;
  return term;
}

function RegressionTable({ model }) {
  return (
    <div className="overflow-x-auto">
      <table className="w-full text-sm">
        <thead>
          <tr className="text-left text-xs uppercase tracking-wide text-gray-400 border-b border-gray-100">
            <th className="py-2 pr-4">Term</th>
            <th className="py-2 pr-4">Coefficient</th>
            <th className="py-2">p-value</th>
          </tr>
        </thead>
        <tbody>
          {model.coefficients.map((c) => (
            <tr key={c.term} className="border-b border-gray-50 last:border-0">
              <td className="py-2 pr-4 text-gray-700">{formatTerm(c.term)}</td>
              <td className="py-2 pr-4 font-medium text-gray-900">{c.coef}</td>
              <td className={`py-2 ${c.p_value < 0.05 ? "text-indigo-600 font-medium" : "text-gray-400"}`}>
                {c.p_value}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function ModelCard({ title, description, model, highlighted }) {
  return (
    <div
      className={`rounded-2xl shadow-sm p-6 ${
        highlighted ? "bg-rose-50/40 border-2 border-rose-200" : "bg-white border border-gray-100"
      }`}
    >
      {highlighted && (
        <div className="text-xs font-medium tracking-widest text-rose-500 uppercase mb-2">Preferred comparison</div>
      )}
      <h3 className="text-lg font-semibold text-gray-900 mb-1">{title}</h3>
      <p className="text-sm text-gray-500 mb-4">{description}</p>
      <div className="flex gap-6 text-sm mb-4">
        <div>
          <div className="text-xs text-gray-400 uppercase tracking-wide">R²</div>
          <div className="font-semibold text-gray-900">{model.r_squared}</div>
        </div>
        <div>
          <div className="text-xs text-gray-400 uppercase tracking-wide">Observations</div>
          <div className="font-semibold text-gray-900">{model.n_obs}</div>
        </div>
      </div>
      <details>
        <summary className="text-xs text-indigo-500 cursor-pointer hover:underline mb-2">
          Full coefficient table
        </summary>
        <div className="mt-3">
          <RegressionTable model={model} />
        </div>
      </details>
    </div>
  );
}

function HighlightStat({ label, value, sublabel, color }) {
  const valueColor = color === "rose" ? "text-rose-600" : "text-indigo-600";
  return (
    <div className="bg-white border border-gray-100 rounded-2xl shadow-sm p-6">
      <div className="text-xs font-medium tracking-widest text-gray-400 uppercase mb-3">{label}</div>
      <div className={`${playfair.className} text-3xl ${valueColor} mb-1.5`}>{value}</div>
      <div className="text-sm text-gray-500">{sublabel}</div>
    </div>
  );
}

const METHOD_STEPS = [
  {
    n: "01",
    title: "Measure strength",
    body: "Give each team a strength marker from its own record in earlier preliminary rounds, rather than treating every team as identical.",
  },
  {
    n: "02",
    title: "Compare like with like",
    body: "Compare teams at a similar strength level across OG, OO, CG and CO simultaneously, instead of pooling every team together.",
  },
  {
    n: "03",
    title: "Recheck the pattern",
    body: "Ask whether the position ordering seen in the pooled stats above still holds once that strength difference is held steady.",
  },
];

export default function AnalyticsPage() {
  const data = loadJson("analytics.json");
  const strengthBands = loadJsonOptional("strength_bands.json");
  const motions = loadJsonOptional("motions.json");
  const keywords = motions ? topKeywords(motions, { topN: 24 }) : [];
  const topics = loadJsonOptional("topics.json");
  const topicTrends = loadJsonOptional("topic_trends.json");
  const positionTopicHeatmap = loadJsonOptional("position_topic_heatmap.json");

  const govStat = data.bench_stats.find((b) => b.bench === "Government");
  const oppStat = data.bench_stats.find((b) => b.bench === "Opposition");
  const openStat = data.half_stats.find((h) => h.half === "Opening");
  const closeStat = data.half_stats.find((h) => h.half === "Closing");

  const overviewStats = [
    { label: "Tournaments", value: data.n_tournaments },
    { label: "Debates analysed", value: data.n_debates_total },
    {
      label: "Team observations in this analysis",
      value: strengthBands ? strengthBands.coverage.n_team_observations_in_sample : "—",
    },
    {
      label: "Debates in this analysis",
      value: strengthBands ? strengthBands.coverage.n_debates_in_sample : "—",
    },
  ];

  const positionData = data.position_stats.map((p) => ({ label: p.position, value: p.avg_points }));
  const benchData = data.bench_stats.map((b) => ({ label: b.bench, value: b.avg_points }));
  const halfData = data.half_stats.map((h) => ({ label: h.half, value: h.avg_points }));

  const bestPosition = data.position_stats.reduce((a, b) => (b.avg_points > a.avg_points ? b : a));
  const worstPosition = data.position_stats.reduce((a, b) => (b.avg_points < a.avg_points ? b : a));

  return (
    <>
      <Nav current="analytics" />
      <main className="max-w-7xl mx-auto px-6 py-16">
        <SectionLabel>Main analysis</SectionLabel>
        <h1 className={`${playfair.className} text-4xl sm:text-5xl leading-tight mb-4`}>
          How do positional outcomes vary with team strength?
        </h1>
        <p className="text-gray-500 max-w-2xl mb-8">
          Every BP debate splits four teams across Opening Government (OG), Opening Opposition (OO), Closing
          Government (CG) and Closing Opposition (CO). This page asks whether the points a team tends to earn from
          each position differ depending on how that team had already been performing before the round —
          separately from whatever the position itself is worth on average.
        </p>

        <StatGrid stats={overviewStats} />

        <div className="mt-10">
          <StrengthBandChart strengthBands={strengthBands} />
        </div>

        <div className="mt-16 pt-12 border-t border-gray-100">
          <SectionLabel>Pooled stats</SectionLabel>
          <h2 className={`${playfair.className} text-2xl sm:text-3xl mb-2 mt-2`}>
            Position, bench and half — across every debate
          </h2>
          <p className="text-gray-500 max-w-2xl mb-6">
            The same average points, pooled across every tournament with confirmed ballots rather than split by
            prior performance. Useful as a baseline, but it can&rsquo;t tell you whether a position&rsquo;s advantage changes
            for stronger or weaker teams — that&rsquo;s what the chart above is for.
          </p>

          <div className="grid grid-cols-2 gap-4 mb-6">
            <HighlightStat
              label="Highest average"
              value={bestPosition.position}
              sublabel={`${bestPosition.avg_points} average points`}
              color="rose"
            />
            <HighlightStat
              label="Lowest average"
              value={worstPosition.position}
              sublabel={`${worstPosition.avg_points} average points`}
              color="indigo"
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6">
            <ComparisonRow
              title="Government vs. Opposition"
              leftStat={{ label: "Government", value: govStat.avg_points }}
              rightStat={{ label: "Opposition", value: oppStat.avg_points }}
              advantage={data.government_advantage}
            />
            <ComparisonRow
              title="Opening vs. Closing"
              leftStat={{ label: "Opening", value: openStat.avg_points }}
              rightStat={{ label: "Closing", value: closeStat.avg_points }}
              advantage={data.opening_advantage}
            />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-6">
            <div className="bg-white border border-gray-100 rounded-2xl shadow-sm p-6">
              <h3 className="text-sm font-semibold text-gray-900 mb-4">By position</h3>
              <BarChart data={positionData} formatValue={(v) => `${v} pts`} />
            </div>
            <div className="bg-white border border-gray-100 rounded-2xl shadow-sm p-6">
              <h3 className="text-sm font-semibold text-gray-900 mb-4">By bench</h3>
              <BarChart data={benchData} formatValue={(v) => `${v} pts`} />
            </div>
            <div className="bg-white border border-gray-100 rounded-2xl shadow-sm p-6">
              <h3 className="text-sm font-semibold text-gray-900 mb-4">By half</h3>
              <BarChart data={halfData} formatValue={(v) => `${v} pts`} />
            </div>
          </div>

          {keywords.length > 0 && (
            <div className="mt-6">
              <CommonKeywords
                keywords={keywords}
                description={`Words appearing most often across the ${motions.length.toLocaleString()} motions behind this analysis.`}
              />
            </div>
          )}
        </div>

        <div className="mt-16 pt-12 border-t border-gray-100">
          <SectionLabel>By topic</SectionLabel>
          <h2 className={`${playfair.className} text-2xl sm:text-3xl mb-2 mt-2`}>
            What are these motions actually about?
          </h2>
          <p className="text-gray-500 max-w-2xl mb-6">
            Every motion is tagged with a topic by a local model (see the README for{" "}
            <code className="bg-gray-50 px-1.5 py-0.5 rounded text-gray-600">scripts/classify_motions.py</code>) -
            the topic set itself is discovered from this corpus rather than picked from a fixed list beforehand.
          </p>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
            <TopicDonut topics={topics} />
            <PositionBalancePanel rows={positionTopicHeatmap} />
          </div>

          <div className="mb-6">
            <TopicPositionHeatmap rows={positionTopicHeatmap} />
          </div>

          <TopicTrendsChart topicTrends={topicTrends} />
        </div>

        <div className="mt-16 pt-12 border-t border-gray-100">
          <SectionLabel>Making a fairer comparison</SectionLabel>
          <h2 className={`${playfair.className} text-2xl sm:text-3xl mb-2 mt-2`}>
            What &ldquo;controlling for team strength&rdquo; means
          </h2>
          <p className="text-gray-500 max-w-2xl mb-8">
            Strong teams may not be spread evenly across positions. The adjustment below separates the effect of{" "}
            <strong className="text-gray-700 font-medium">which team debated</strong> from the effect of{" "}
            <strong className="text-gray-700 font-medium">where they debated</strong>.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 mb-8">
            {METHOD_STEPS.map((step) => (
              <div key={step.n} className="bg-white border border-gray-100 rounded-2xl shadow-sm p-6">
                <div className={`${playfair.className} text-2xl text-rose-400 mb-2`}>{step.n}</div>
                <h3 className="font-semibold text-gray-900 mb-2">{step.title}</h3>
                <p className="text-sm text-gray-500">{step.body}</p>
              </div>
            ))}
          </div>

          <ModelCard
            title="Leakage-safe model (prior strength / pre-round rank)"
            description="Controls for each team's rank going into the round, using prior rounds only — the clearest test of whether position itself is associated with the result. A second model that instead used each team's final tournament rank was checked against this one during development; it uses information not available at debate time and inflated the apparent R² roughly tenfold, which is why it isn't shown here as a result in its own right."
            model={data.regression.leakage_safe}
            highlighted
          />
        </div>
      </main>
    </>
  );
}